version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Map backend port
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
